title: Bem vindo sonegador
author: PWA
email: paulowilliam.alvin@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Repositório de arquivos e informações da turma de ciências contábeis 2019/1 UFMT Campus Cuiabá.
# social links
github_username:  willalvin # DO NOT include the @ character, or else the build will fail!
facebook_username: willalvin 
instagram_username: willalvin

show_excerpts: true # set to false to remove excerpts on the homepage
