title: Bem vindo sonegador
author: Paulo William Alvin
email: paulowilliam.alvin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Repositório de arquivos e informações da turma de ciências contábeis 2019/1 UFMT Campus Cuiabá.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  willalvin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
