title: Bem-vindo Sonegador
author: PWA
email: paulowilliam.alvin@gmail.com
theme: minima 

minima:
  date_format: "%-d de %b de %Y"

description: > # this means to ignore newlines until "baseurl:"
  Repositório de arquivos e informações da turma de Ciências Contábeis 2019/1 UFMT Campus Cuiabá.

# social links
twitter_username: paulowalvin # DO NOT include the @ character, or else the build will fail!
linkedin_username: paulowalvin # DO NOT include the @ character, or else the build will fail!
facebook_username: paulowalvin
instagram_username: paulowalvin

show_excerpts: false # set to false to remove excerpts on the homepage

